### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by mrinal18** [yhw-yhw/TalkSHOW#27]
Hello,

I am getting this Value Error while trying to run your scripts by following the README.md

`ValueError: need at least one array to concatenate`

this is the traceback for the error :

```
Traceback (most recent call last):
  File "scripts/train.py", line 10, in <module>
    trainer = Trainer()
  File "/data/users1/user/TalkSHOW/trainer/Trainer.py", line 72, in __init__
    self.init_dataloader()
  File "/data/users1/user/TalkSHOW/trainer/Trainer.py", line 168, in init_dataloader
    config=self.config
  File "/data/users1/user/TalkSHOW/data_utils/dataloader_torch.py", line 255, in __init__
    self.complete_data=np.concatenate(self.complete_data, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate


```

for now, i am trying to load only two speakers, oliver and conan to make sure everything works smoothly. 
 
I have changed this in `apply_split.py` : 

```
speakers = ['oliver', 'conan']
```

and did the same in `body_vq.json`
and given my data_root as the dataset path

Kindly let me know what is the fix for this issue? 

Thanks a bunch in advance.

**Comment by BoyiZhao** [comment]
I have the same problem, bro. Have you solved this? 😭

**Comment by Symbolzzz** [comment]
Same problem, how to fix this😭

**Comment by Symbolzzz** [comment]
> I have the same problem, bro. Have you solved this? 😭

I solve this problem by unzip the dataset again, maybe there is something lost in the process of the unzip.

don't forget to run `data_utils/apply_split.py` before your training.

**Comment by BoyiZhao** [comment]
> > I have the same problem, bro. Have you solved this? 😭
> 
> I solve this problem by unzip the dataset again, maybe there is something lost in the process of the unzip.
> 
> don't forget to run `data_utils/apply_split.py` before your training.

Thank you bro. I have solved it before

**Comment by zjy-2020** [comment]
> > > I have the same problem, bro. Have you solved this? 😭
> > 
> > 
> > I solve this problem by unzip the dataset again, maybe there is something lost in the process of the unzip.
> > don't forget to run `data_utils/apply_split.py` before your training.
> 
> Thank you bro. I have solved it before

Hello, have you solved it
